https://www.perplexity.ai/search/045ecda7-23bf-4d76-9155-fcb886e2425e

In [5]:
import numpy as np
np.random.random()
np.random.random(3)
np.random.random(size=3)
np.random.random((3, 4))
np.random.random(size=(3,4))

array([[0.45538222, 0.88721317, 0.82153768, 0.21595103],
       [0.87195637, 0.53168564, 0.02020151, 0.03129179],
       [0.08793208, 0.51225591, 0.08768134, 0.23232317]])

In [2]:
from numpy.random import normal 

normal_value = normal(size=(3, 4))
#normal_value =normal(3,4)
#ndarray常用的實體屬性
type(normal_value)
normal_value.ndim
normal_value.size
normal_value.shape
normal_value.dtype

dtype('float64')

numpy.random.normal(loc=0.0, scale=1.0, size=None)
loc：分佈的均值（預設為 0.0）。
scale：分佈的標準差（預設為 1.0）。
size：輸出陣列的形狀，可以是整數或元組（tuple）。
在 normal_value = normal(size=(3, 4)) 中：
你明確指定了 size=(3, 4)，表示生成一個形狀為 (3, 4) 的二維陣列，包含從正態分佈中抽取的隨機數。
這是正確的用法，因為 size 參數需要明確指定輸出陣列的形狀。
在 normal_value = normal(3, 4) 中：
這種寫法試圖將 3 和 4 作為前兩個參數傳遞給 normal 函數。
根據 normal 的參數順序，3 會被解釋為 loc（均值），4 會被解釋為 scale（標準差），而不是形狀。
這會導致生成一個單一的隨機數（因為 size 預設為 None），而不是形狀為 (3, 4) 的陣列。

節省命名空間
只導入需要的函數（如 normal），可以避免把整個 numpy.random 模組的所有函數都加進來，讓你的程式碼更簡潔、命名空間更乾淨，減少名稱衝突的機會。

提高可讀性
直接使用 normal()，而不是每次都寫 np.random.normal()，讓程式碼更精簡、易讀。這對於只需要用到一兩個隨機函數的腳本特別有幫助。

明確指出用途
這種寫法清楚地表明你只會用到 normal 這個功能，其他的隨機數生成函數（如 randint、random 等）都不會用到，讓協作者一看就明白你的需求。

效能差異微乎其微
在現代 Python 中，從模組中導入單一函數和導入整個模組在效能上差異很小，主要是為了程式碼組織和維護性考量。

In [18]:
#ndarray,陣列運算
normal_value * 10

array([[ 12.58996287,  15.05783547,   8.69203655, -11.04591528],
       [  6.75457144,  14.75519745,   1.63740728,  -6.23245812],
       [ -3.19942131,  -5.97713143,   7.06584288,  16.16075302]])

In [21]:
#ndarray,的統計
normal_value.sum()
normal_value.sum(axis=0)
normal_value.sum(axis=1)

array([2.52939196, 1.69147181, 1.40500432])